"""Test the fixed-point C Goertzel (firmware/goertzel.c) against
   1. a bit-exact integer model (any mismatch = firmware bug),
   2. the float reference goertzel_envelope() in ir_dsp.py,
   3. end-to-end NEC decoding through the existing adaptive slicer.

  python test_goertzel_fixed.py                  # LTspice exports + synthetic sweep
  python test_goertzel_fixed.py ../sim/exports/Draft4_gain_20nA.txt
  set GCC=C:/msys64/ucrt64/bin/gcc.exe to override the compiler path.
"""
import math, os, sys, subprocess, tempfile
import numpy as np
import ir_dsp as d

HERE = os.path.dirname(os.path.abspath(__file__))
FW = os.path.join(HERE, "firmware")
GCC = os.environ.get("GCC", r"C:/msys64/ucrt64/bin/gcc.exe")
EXE = os.path.join(FW, "gz_run.exe")

N, HOP, LOG2N = 128, 32, 7
ADC_BITS, VREF = 12, 3.3
LSB = VREF / 2 ** ADC_BITS
HANN_Q15 = np.round(np.hanning(N) * 32767).astype(np.int64)
COEFF_Q14 = int(round(2 * np.cos(2 * np.pi * d.FC / d.FS) * 16384))
HANN_SUM = int(HANN_Q15.sum())
EXPECT = [(0x04, 0x08), "REPEAT"]

# adaptive_slicer() defaults, at the Goertzel output rate
FE = d.FS // HOP                                  # 15625 Hz -> 64 us per envelope sample
SL_WARMUP = int(1e-3 * FE)
SL_INIT_N = max(8, int(2e-3 * FE))
q16 = lambda tau: int(round((1 - np.exp(-1 / (tau * FE))) * 65536))
SL_A_ATT, SL_A_FLR, SL_A_DEC = q16(30e-6), q16(20e-3), q16(150e-3)
SL_LO_Q16, SL_HI_Q16, SL_SNR = int(round(0.35 * 65536)), int(round(0.5 * 65536)), 4

# I/Q detector (firmware/iq.c): DC blocker -> 38 kHz mixer -> CIC3 /8 -> FIR /4.
# Same 15625 Hz output rate as the Goertzel, so the slicer is shared.
IQ_R1, IQ_R2, IQ_ORDER, IQ_DC_SHIFT = 8, 4, 3, 8
IQ_NTAPS, IQ_CUTOFF, IQ_BETA = 48, 3000, 6
IQ_LO_N = 250                                      # 38k/500k = 19/250: LO repeats every 250 samples
assert IQ_R1 * IQ_R2 == HOP and d.FC * IQ_LO_N % d.FS == 0
_ph = 2 * np.pi * d.FC / d.FS * np.arange(IQ_LO_N)
IQ_COS_Q14 = np.round(np.cos(_ph) * 16384).astype(np.int64)
IQ_SIN_Q14 = np.round(np.sin(_ph) * 16384).astype(np.int64)


def iq_fir():
    from scipy import signal
    h = signal.firwin(IQ_NTAPS, IQ_CUTOFF, window=("kaiser", IQ_BETA), fs=d.FS / IQ_R1)
    return np.round(h * 32768).astype(np.int64)


IQ_FIR_Q15 = iq_fir()
IQ_CIC_SHIFT = IQ_ORDER * int(np.log2(IQ_R1))      # CIC gain R1^ORDER = 2^9
assert 2 ** IQ_CIC_SHIFT == IQ_R1 ** IQ_ORDER
assert np.abs(IQ_FIR_Q15).sum() * 32767 < 2 ** 31, "FIR accumulator could overflow int32"


def c_array(ctype, name, size, vals, per_row=10):
    rows = ",\n".join("    " + ", ".join(f"{v:6d}" for v in vals[i:i + per_row])
                      for i in range(0, len(vals), per_row))
    return f"static const {ctype} {name}[{size}] = {{\n{rows}\n}};\n"


def write_tables():
    assert d.FS % HOP == 0 and 1_000_000 % FE == 0
    rows = ",\n".join("    " + ", ".join(f"{v:5d}" for v in HANN_Q15[i:i + 8])
                      for i in range(0, N, 8))
    iq = "\n".join([c_array("int16_t", "IQ_COS_Q14", "IQ_LO_N", IQ_COS_Q14),
                    c_array("int16_t", "IQ_SIN_Q14", "IQ_LO_N", IQ_SIN_Q14),
                    c_array("int16_t", "IQ_FIR_Q15", "IQ_NTAPS", IQ_FIR_Q15, 8)])
    src = f"""/* Generated by test_goertzel_fixed.py -- do not edit. */
#ifndef GZ_TABLES_H
#define GZ_TABLES_H
#include <stdint.h>

#define GZ_N            {N}
#define GZ_LOG2N        {LOG2N}
#define GZ_HOP          {HOP}
#define GZ_COEFF_Q14    {COEFF_Q14}   /* 2*cos(2*pi*{d.FC}/{d.FS}) */
#define GZ_HANN_SUM_Q15 {HANN_SUM}

static const int16_t GZ_HANN_Q15[GZ_N] = {{
{rows}
}};

/* adaptive slicer (ir_dsp.adaptive_slicer defaults) at {FE} Hz envelope rate */
#define IR_ENV_PERIOD_US {1_000_000 // FE}
#define SL_WARMUP        {SL_WARMUP}    /* envelope samples skipped (1 ms) */
#define SL_INIT_N        {SL_INIT_N}    /* samples in the initial floor median (2 ms) */
#define SL_A_ATT_Q16     {SL_A_ATT}   /* tau 30 us */
#define SL_A_FLR_Q16     {SL_A_FLR}     /* tau 20 ms */
#define SL_A_DEC_Q16     {SL_A_DEC}      /* tau 150 ms */
#define SL_LO_Q16        {SL_LO_Q16}
#define SL_HI_Q16        {SL_HI_Q16}
#define SL_SNR           {SL_SNR}

/* I/Q detector: DC blocker, 38 kHz mixer, CIC{IQ_ORDER} /{IQ_R1}, {IQ_NTAPS}-tap FIR /{IQ_R2}
 * (Kaiser beta {IQ_BETA}, cutoff {IQ_CUTOFF} Hz at {d.FS // IQ_R1} Hz) */
#define IQ_R1        {IQ_R1}
#define IQ_R2        {IQ_R2}
#define IQ_ORDER     {IQ_ORDER}
#define IQ_CIC_SHIFT {IQ_CIC_SHIFT}     /* log2(R1^ORDER) */
#define IQ_DC_SHIFT  {IQ_DC_SHIFT}     /* DC blocker time constant 2^{IQ_DC_SHIFT} samples */
#define IQ_NTAPS     {IQ_NTAPS}
#define IQ_LO_N      {IQ_LO_N}

{iq}
#endif
"""
    with open(os.path.join(FW, "gz_tables.h"), "w", newline="\n") as f:
        f.write(src)


IR_EXE = os.path.join(FW, "ir_run.exe")


def build():
    write_tables()
    cc = [GCC, "-std=c99", "-O2", "-Wall", "-Wextra", "-Werror", "-static"]
    env = dict(os.environ)          # MSYS2 gcc needs its own bin dir on PATH
    env["PATH"] = os.path.dirname(GCC) + os.pathsep + env.get("PATH", "")
    for out, srcs in ((EXE, ["goertzel.c", "iq.c", "gz_run.c"]),
                      (IR_EXE, ["goertzel.c", "iq.c", "ir_rx.c", "ir_run.c"])):
        subprocess.run(cc + ["-o", out] + srcs, cwd=FW, env=env, check=True)


def run_c(codes, detector="goertzel"):
    """Envelope (amp_q3) from the C detector: 'goertzel' or 'iq'."""
    with tempfile.TemporaryDirectory() as td:
        fi, fo = os.path.join(td, "in.u16"), os.path.join(td, "out.i32")
        codes.astype("<u2").tofile(fi)
        flag = ["-iq"] if detector == "iq" else []
        subprocess.run([EXE] + flag + [fi, fo], check=True, capture_output=True)
        return np.fromfile(fo, dtype="<i4").astype(np.int64)


def rshift_r(x, s):
    return (x + (1 << (s - 1))) >> s


def model(codes):
    """Bit-exact integer model of gz_block(), vectorised over blocks."""
    fr = np.lib.stride_tricks.sliding_window_view(codes.astype(np.int64), N)[::HOP]
    mean = (fr.sum(axis=1) + N // 2) >> LOG2N
    xw = rshift_r((fr - mean[:, None]) * HANN_Q15, 12)
    s1 = np.zeros(len(fr), np.int64); s2 = np.zeros(len(fr), np.int64)
    for n in range(N):
        s1, s2 = xw[:, n] + rshift_r(COEFF_Q14 * s1, 14) - s2, s1
    p = np.maximum(s1 * s1 + s2 * s2 - rshift_r(COEFF_Q14 * s1, 14) * s2, 0)
    mag = np.array([math.isqrt(int(v)) for v in p], np.int64)   # floor, like isqrt64()
    return ((mag << 1) << 15) // HANN_SUM


def to_codes(v):
    return np.clip(np.round(v / LSB), 0, 2 ** ADC_BITS - 1).astype(np.int64)


def fmt(frames):
    return "; ".join("REPEAT" if f["repeat"] else f"0x{f['addr']:02X}/0x{f['cmd']:02X}"
                     for f in frames) or "nothing"


def ok(frames):
    got = ["REPEAT" if f["repeat"] else (f["addr"], f["cmd"]) for f in frames]
    return got == EXPECT


def check(name, codes):
    amp_c = run_c(codes)
    amp_m = model(codes)
    exact = len(amp_c) == len(amp_m) and np.array_equal(amp_c, amp_m)

    t_ref, amp_ref = d.goertzel_envelope(codes * LSB)          # volts
    amp_fix = amp_c / 8.0 * LSB                                  # volts
    err = np.max(np.abs(amp_fix - amp_ref)) / LSB                # in ADC codes
    fr_ref = d.decode(t_ref, amp_ref)[0]
    fr_fix = d.decode(t_ref, amp_fix)[0]
    peak = np.max(amp_ref) / LSB
    print(f"{name:34s} bit-exact {'yes' if exact else 'NO '} | peak {peak:6.1f} codes, "
          f"max err {err:5.2f} codes | float: {fmt(fr_ref):22s} {'OK ' if ok(fr_ref) else 'BAD'} "
          f"| fixed: {fmt(fr_fix):22s} {'OK' if ok(fr_fix) else 'BAD'}")
    return exact and (ok(fr_fix) == ok(fr_ref))


def main():
    build()
    print(f"built {EXE}  (coeff Q14 = {COEFF_Q14}, Hann sum Q15 = {HANN_SUM})\n")
    files = sys.argv[1:] or [os.path.join(HERE, "..", "sim", "exports", f) for f in
                             ("Draft3_nec.txt", "Draft4_gain.txt", "Draft4_gain_20nA.txt")]
    good = True
    for f in files:
        if not os.path.exists(f):
            print(f"skip {f} (missing)"); continue
        _, v = d.load_ltspice_txt(f, "V(tia)")
        good &= check("LTspice " + os.path.basename(f), to_codes(v))
    if len(sys.argv) == 1:
        seg = d.nec_timeline(0x04, 0x08, repeats=1)
        for isig in (10e-9, 20e-9, 30e-9, 40e-9, 80e-9):
            _, v, _ = d.synth_tia(seg, i_sig=isig, interferer=0.1e-6)
            good &= check(f"synthetic {isig*1e9:.0f} nA + 100 nA @45k", to_codes(v))
    print("\nPASS" if good else "\nFAIL")
    return 0 if good else 1


if __name__ == "__main__":
    sys.exit(main())
